services: 
  app:
    image: node:16
    container_name: every-todo-app
    ports: 
      - 3000:3000
    tty: true        
    volumes:
      - ./:/app
      - /app/.next/
      
  mongodb:
    image: mongo
    restart: always
    container_name: every-todo-mongodb
    ports:
      - 27017:27017
    extra_hosts:
      - mongodb:0.0.0.0 
    command: ["--replSet", "every-todo-app-set", "--bind_ip_all"]
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d:ro
